image: lightandlight/purescript:0.11.5

stages:
  - install
  - build
  - test
  - github
  - publish
  
cache:
  paths:
    - bower_components/
    - output/
  
install:
  stage: install
  tags:
    - purescript
  script:
    - bower install

build:
  stage: build
  tags:
    - purescript
  script:
    - pulp build

test:
  stage: test
  tags:
    - purescript
  script:
    - bower list --json > resolutions.json
    - purs publish --manifest bower.json --resolutions resolutions.json --dry-run
    
github:
  stage: github
  tags:
    - purescript
  script:
    - git config push.default matching
    - git remote add github https://lightandlight:$GITHUB_TOKEN@github.com/lightandlight/$CI_PROJECT_NAME.git
    - git push github master --tags
    
pursuit:
  stage: publish
  tags:
    - purescript
  only:
    - tags
  script:
    - echo "$GITHUB_TOKEN" | pulp login
    - git checkout $CI_COMMIT_REF_NAME
    - echo "y" | pulp publish --no-push
